const Issue = require("../models/Issue");
const Society = require("../models/Society");
const MaintenanceTask = require("../models/MaintenanceTask");

/*
==================================================
Convert overdue maintenance into Issues
==================================================
*/

async function generateOverdueMaintenanceIssues() {

    let generated = 0;

    const overdueTasks = await MaintenanceTask.find({
        deadline: {
            $lte: new Date()
        },
        status: {
            $in: [
                "SCHEDULED",
                "IN_PROGRESS",
                "OVERDUE"
            ]
        },
        autoGeneratedIssue: null
    }).populate("societyId");

    for (const task of overdueTasks) {

        const society = task.societyId;

        if (!society) continue;

        const exists = await Issue.findOne({

            societyId: society._id,

            maintenanceTaskId: task._id,

            status: {
                $ne: "Resolved"
            }

        });

        if (exists) {

            if (task.status !== "CONVERTED_TO_ISSUE") {

                task.status = "CONVERTED_TO_ISSUE";
                task.autoGeneratedIssue = exists._id;
                await task.save();

            }

            continue;

        }

        const issue = await Issue.create({

            creator: society.admin,

            societyId: society._id,

            maintenanceTaskId: task._id,

            title: task.title,

            description:
                task.description ||
                `Routine maintenance "${task.title}" missed its deadline.`,

            category: task.category || "Maintenance",

            inferredReason:
                "Scheduled maintenance deadline exceeded.",

            severityScore: 5,

            priority: task.priority || "MEDIUM",

            status: "Open",

            location: task.location?.coordinates?.length === 2
                ? task.location
                : society.location,

            requiredApprovalVotes: 0,

            requiredResolutionVotes: 20,

            timeline: [
                {
                    action: "MAINTENANCE_OVERDUE",
                    status: "Open",
                    note: "Auto-generated from overdue maintenance task.",
                    performedBy: society.admin,
                    metadata: {
                        maintenanceTaskId: task._id
                    }
                }
            ],

            history: [
                {
                    action: "MAINTENANCE_OVERDUE",
                    status: "Open",
                    note: "Auto-generated from overdue maintenance task.",
                    performedBy: society.admin,
                    metadata: {
                        maintenanceTaskId: task._id
                    }
                }
            ]

        });

        task.status = "CONVERTED_TO_ISSUE";
        task.autoGeneratedIssue = issue._id;
        await task.save();

        generated++;

    }

    await generateLegacyScheduleIssues();

    return generated;

}

async function generateLegacyScheduleIssues() {

    const societies = await Society.find({});

    for (const society of societies) {

        if (!society.maintenanceSchedule) continue;

        for (const task of society.maintenanceSchedule) {

            if (task.completed) continue;

            if (!task.deadline) continue;

            if (new Date(task.deadline) > new Date()) continue;

            const exists = await Issue.findOne({

                societyId: society._id,

                maintenanceTaskId: task._id,

                status: {
                    $ne: "Resolved"
                }

            });

            if (exists) continue;

            await Issue.create({

                creator: society.admin,

                societyId: society._id,

                maintenanceTaskId: task._id,

                title: task.taskName,

                description:
                    `Routine maintenance "${task.taskName}" missed its deadline.`,

                category: "Maintenance",

                inferredReason:
                    "Scheduled maintenance deadline exceeded.",

                severityScore: 5,

                priority: "MEDIUM",

                status: "Open",

                location: society.location,

                requiredApprovalVotes: 0,

                requiredResolutionVotes: 20

            });

        }

    }

}

/*
==================================================
Upcoming Maintenance
==================================================
*/

async function getUpcomingMaintenance(societyId) {

    const tasks = await MaintenanceTask.find({
        societyId,
        status: {
            $ne: "COMPLETED"
        }
    }).sort({
        deadline: 1
    });

    if (tasks.length) return tasks;

    const society = await Society.findById(societyId);

    if (!society) return [];

    return society.maintenanceSchedule
        .filter(task => !task.completed)
        .sort((a, b) => new Date(a.deadline) - new Date(b.deadline));

}

/*
==================================================
Mark Completed
==================================================
*/

async function markMaintenanceCompleted(
    societyId,
    taskId
) {

    const task = await MaintenanceTask.findOne({
        _id: taskId,
        societyId
    });

    if (task) {

        task.status = "COMPLETED";
        task.completedAt = new Date();

        await task.save();

        return true;

    }

    const society = await Society.findById(societyId);

    if (!society) return false;

    const legacyTask = society.maintenanceSchedule.id(taskId);

    if (!legacyTask) return false;

    legacyTask.completed = true;

    await society.save();

    return true;

}

module.exports = {

    generateOverdueMaintenanceIssues,

    getUpcomingMaintenance,

    markMaintenanceCompleted

};
