// backend/models/MaintenanceTask.js

const mongoose = require("mongoose");

const maintenanceTaskSchema = new mongoose.Schema(
{
    societyId:
    {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Society",
        required: true,
        index: true
    },

    createdBy:
    {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true
    },

    title:
    {
        type: String,
        required: true,
        trim: true
    },

    description:
    {
        type: String,
        default: ""
    },

    category:
    {
        type: String,
        enum:
        [
            "Water Tank",
            "Drainage",
            "Lift",
            "Electrical",
            "Road",
            "Security",
            "Cleaning",
            "Fire Safety",
            "Garden",
            "Other"
        ],
        default: "Other"
    },

    priority:
    {
        type: String,
        enum:
        [
            "LOW",
            "MEDIUM",
            "HIGH",
            "CRITICAL"
        ],
        default: "MEDIUM"
    },

    scheduledDate:
    {
        type: Date,
        required: true
    },

    deadline:
    {
        type: Date,
        required: true
    },

    assignedTo:
    {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        default: null
    },

    location:
    {
        type:
        {
            type: String,
            enum: ["Point"],
            default: "Point"
        },
        coordinates:
        {
            type: [Number],
            default: undefined
        }
    },

    status:
    {
        type: String,
        enum:
        [
            "SCHEDULED",
            "IN_PROGRESS",
            "COMPLETED",
            "OVERDUE",
            "CONVERTED_TO_ISSUE"
        ],
        default: "SCHEDULED"
    },

    autoGeneratedIssue:
    {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Issue",
        default: null
    },

    completedAt:
    {
        type: Date,
        default: null
    },

    remarks:
    {
        type: String,
        default: ""
    }

},
{
    timestamps: true
});

maintenanceTaskSchema.index({
    societyId: 1,
    status: 1
});

maintenanceTaskSchema.index({
    deadline: 1
});

maintenanceTaskSchema.index({
    scheduledDate: 1
});

maintenanceTaskSchema.index({
    location: "2dsphere"
});

module.exports = mongoose.model(
    "MaintenanceTask",
    maintenanceTaskSchema
);
