// backend/controllers/maintenanceBoardController.js

const MaintenanceTask = require("../models/MaintenanceTask");
const Issue = require("../models/Issue");

/*
=========================================================
Public Maintenance Board
Phase 1 Requirement
=========================================================
*/

const getMaintenanceBoard = async (req, res) => {

    try {

        const tasks = await MaintenanceTask.find({

            societyId: req.user.societyId

        })
        .sort({
            deadline: 1
        });

        const board = await Promise.all(

            tasks.map(async task => {

                const overdue =

                    task.deadline < new Date() &&
                    task.status !== "COMPLETED";

                let linkedIssue = null;

                if (task.autoGeneratedIssue) {

                    linkedIssue = await Issue.findOne({

                        _id: task.autoGeneratedIssue,

                        societyId: req.user.societyId

                    }).select(

                        "status category severityScore"

                    );

                }

                return {

                    _id: task._id,

                    title: task.title,

                    description: task.description,

                    category: task.category,

                    priority: task.priority,

                    scheduledDate: task.scheduledDate,

                    deadline: task.deadline,

                    status: task.status,

                    overdue,

                    linkedIssue

                };

            })

        );

        res.json({

            success: true,

            board

        });

    }
    catch (err) {

        console.error(err);

        res.status(500).json({

            success: false,

            error: err.message

        });

    }

};

/*
=========================================================
Upcoming Maintenance
=========================================================
*/

const getUpcomingMaintenance = async (req, res) => {

    try {

        const today = new Date();

        const upcoming = await MaintenanceTask.find({

            societyId: req.user.societyId,

            deadline: {

                $gte: today

            },

            status: {

                $ne: "COMPLETED"

            }

        })
        .sort({

            deadline: 1

        });

        res.json({

            success: true,

            upcoming

        });

    }
    catch (err) {

        console.error(err);

        res.status(500).json({

            success: false,

            error: err.message

        });

    }

};

/*
=========================================================
Overdue Maintenance
=========================================================
*/

const getOverdueMaintenance = async (req, res) => {

    try {

        const overdue = await MaintenanceTask.find({

            societyId: req.user.societyId,

            deadline: {

                $lt: new Date()

            },

            status: {

                $ne: "COMPLETED"

            }

        })
        .sort({

            deadline: 1

        });

        res.json({

            success: true,

            overdue

        });

    }
    catch (err) {

        console.error(err);

        res.status(500).json({

            success: false,

            error: err.message

        });

    }

};

module.exports = {

    getMaintenanceBoard,

    getUpcomingMaintenance,

    getOverdueMaintenance

};
